import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { Providers } from "./Providers";
import Provider from "@/components/Provider";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "BelanjaYukk",
  description: "Generated by create next app",
  category: "ecommerce",
  authors: [{ name: "Alqorni bayo" }],
  creator: "Alqorni bayo",
  icons: {
    icon: "/icons/icon logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scrollbar-thumb-orange-600 scrollbar-thin overflow-y-scroll scrollbar-track-orange-200"
    >
      <body className={poppins.className}>
        <Provider>
          <Providers>{children}</Providers>
        </Provider>
      </body>
    </html>
  );
}
