import { BreadcrumbComponent } from "@/components/fragments/BreadcrumbComponent";
import Header from "@/components/layouts/Header";
import Sidebar from "@/components/layouts/Sidebar";
import Provider from "@/components/Provider";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Admin BelanjaYukk",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Provider>
        <div className="flex bg-slate-100 w-full h-screen relative ">
          <Sidebar />
          <div
            className="w-full
        transition-all relative overflow-x-hidden"
          >
            <Header />
            <BreadcrumbComponent />
            {children}
          </div>
        </div>
      </Provider>
    </div>
  );
}
